#########################################################################
#### filename:  main.yml                                             ####
#### path:      ~/src/deploy/roles/drupal/handlers/main.yml      ####
#### role:      drupal development                                   ####
#### purpose:   handlers are called by other plays                   ####
#### version:   07/16/2014                                           ####
#########################################################################

---

- name: Config | Update timezone on {{ v_host }}
  sudo: yes
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Config | Reload ssh daemon on {{ v_host }}
  sudo: yes
  service: name=ssh state=restarted

- name: reload apache2 daemon
  sudo: yes
  service: name=apache2 state=restarted

- name: reload nginx daemon
  sudo: yes
  service: name=nginx state=restarted

- name: reload php5-fpm daemon
  sudo: yes
  service: name=php5-fpm state=restarted

- name: reload mysql daemon
  sudo: yes
  service: name=mysql state=restarted

- name: Drupal | Initiate composer global update on {{ v_host }}
  shell: /usr/local/bin/composer global update --no-interaction --no-ansi
  sudo_user: "{{ composer_user }}"
