# vim:fdm=marker
---

  ##########################################################
  #  filename: os_config.yml 	                             #
  #  path:     ~/.provision/playbook/roles/osx/tasks/  #
  #  version:  04/05/2015                                  #
  #  purpose:  os config                                   #
  ##########################################################

- name: os config | starting playlist
  tags: [os_config, voice]
  osx_say: msg="os config playlist is starting" voice={{ v_voice }}

- name: os config | set computer name
  tags: [os_config]
  sudo: yes
  command: "{{ item }} {{ mba_name }}"
  with_items:
    - scutil --set ComputerName
    - scutil --set HostName
    - scutil --set LocalHostName
    - defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string

- name: os config | show additional menu bar items
  tags: [os_config]
  command: 'open /System/Library/CoreServices/Menu\ Extras/"{{ item }}"'
  with_items:
    - Bluetooth.menu
    - TimeMachine.menu
#    - Displays.menu
#    - Volume.menu

- name: os config | disable transparency in menu bar and elsewhere
  tags: [os_config]
  command: defaults write com.apple.universalaccess reduceTransparency -bool true

- name: os config | bluetooth trackpad settings
  tags: [os_config, trackpad]
  command: defaults write com.apple.{{ item[0] }} {{ item[1] }}
  with_nested:
    - ['driver.AppleBluetoothMultitouch.trackpad', 'AppleMultitouchTrackpad']
    - ['Clicking -bool true', # enable 1-finger tap to click
      'TrackpadRightClick -bool true', # enable 2-finger tap for right click
      'TrackpadThreeFingerTapGesture -int 2', # enable 3-finger term lookup
      'TrackpadThreeFingerDrag -bool true', # enable 3-finger drag
      'TrackpadPinch -bool true', # enable pinch zoom
      'TrackpadTwoFingerDoubleTapGesture -bool true', # enable smart zoom
      'TrackpadRotate -bool true', # enable rotate
      'TrackpadTwoFingerFromRightEdgeSwipeGesture -int 3', # 2-finger notifications
      'TrackpadFourFingerHorizSwipeGesture -int 2', # 4-finger swipe between apps
      'TrackpadFourFingerVertSwipeGesture -int 2',
      'TrackpadFourFingerPinchGesture -int 2',
      'TrackpadFiveFingerPinchGesture -int 2']

- name: os config | set trackpad/mouse acceleration
  tags: [os_config]
  command: defaults write -g {{ item }}
  with_items:
    - com.apple.trackpad.scaling -float 2.5
    - com.apple.mouse.scaling -float 2.5

- name: os config | ambient light settings
  tags: [os_config]
  sudo: yes
  command: defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor {{ item }}
  with_items:
    - '"Automatic Keyboard Enabled" -bool true'
    - '"Keyboard Dim Time" -int 300'
    - '"Automatic Display Enabled" -bool true'

- name: os config | dictation settings
  tags: [os_config, dictation]
  command: defaults write com.apple.speech.recognition.AppleSpeechRecognition.prefs {{ item }}
  with_items:
    - DictationIMMasterDictationEnabled -bool true
    - DictationIMUseOnlyOfflineDictation -bool true

- name: os config | lock screen message
  tags: [os_config, lock]
  sudo: yes
  command: defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText '"░░░░░░░░  ☎  {{ admin_phone }}  ░░░░░░░░"'

- name: os config | screensaver settings
  tags: [os_config, screensaver]
  command: defaults write com.apple.screensaver {{ item }}
  with_items:
    - askForPassword -int 1
    - askForPasswordDelay -int 60

- name: os config | screensaver settings
  tags: [os_config, screensaver]
  command: defaults -currentHost write com.apple.screensaver {{ item }}
  with_items:
    - idleTime -int 600
    - moduleDict -dict moduleName -string "Arabesque" path -string "/System/Library/Screen Savers/Arabesque.qtz" type -int 1

- name: os config | energy saver settings
  tags: [os_config, energy]
  sudo: yes
  command: pmset {{ item }}
  with_items:
    - -b lessbright 1 sleep 20 displaysleep 15 disksleep 0 womp 1 darkwakes 0
    - -c sleep 30 displaysleep 20 disksleep 0 womp 1 darkwakes 0 # ac power

- name: os config | finder settings
  tags: [os_config, finder]
  command: defaults write com.apple.finder {{ item }}
  with_items:
   # - AppleShowAllFiles -bool true # show hidden files
    - FXDefaultSearchScope -string "SCcf" # search @current folder
    - FXEnableExtensionChangeWarning -bool false # no extension rename warning
    - FXInfoPanesExpanded -dict General -bool true Privileges -bool true
    - FXPreferredViewStyle -string "clmv" # column view; Nlsv icnv Flwv
    - _FXShowPosixPathInTitle -bool true # POSIX path as Finder window title
    - NewWindowTarget -string "PfHm" # new finder window points home
    - NewWindowTargetPath -string "file://$HOME/" # path to home
    - OpenWindowForNewRemovableDisk -bool false # show finder @new volume mount
    - QLEnableTextSelection -bool true # allow text selection in Quick Look
    - QuitMenuItem -bool true # allow quitting via ⌘ + Q
    - ShowExternalHardDrivesOnDesktop -bool true # show desktop icons
    - ShowHardDrivesOnDesktop -bool true # "
    - ShowMountedServersOnDesktop -bool true # "
    - ShowPathbar -bool true # show path bar
    - ShowRemovableMediaOnDesktop -bool true # "
    - ShowStatusBar -bool true # show status bar
    - ShowTabView -bool true # show tabs
    - WarnOnEmptyTrash -bool false # disable empty trash warning

- name: os config | dock settings
  tags: [os_config, dock]
  command: defaults write com.apple.dock {{ item }}
  with_items:
    - autohide -bool true # automatically hide and show the Dock
    - autohide-delay -int 0 # remove the auto-hiding Dock delay
    - autohide-time-modifier -float 0 # remove the auto-hiding Dock delay
    - enable-spring-load-actions-on-all-items -bool true # enable spring loading
    - expose-animation-duration -float 0.1 # speed up Mission Control animations
    - dashboard-in-overlay -bool true # don’t show Dashboard as a Space
    - magnification -bool true # use magnification
    - mcx-disabled -bool true # disable Dashboard
    - mineffect -string "scale" # minimize/maximize window effect
    - minimize-to-application -bool true # minimize windows to app’s icon
    - mouse-over-hilite-stack -bool true # enable highlight effect on dock grid
    - orientation -string "bottom"
    - show-process-indicators -bool true # show indicator lights for open apps
    - showAppExposeGestureEnabled -bool true
    - showDesktopGestureEnabled -bool true
    - showhidden -bool true # make Dock icons of hidden apps translucent
    - showLaunchpadGestureEnabled -bool true
    - showMissionControlGestureEnabled -bool true
    - tilesize -int 55 # dock icon size
    - wvous-bl-corner -int 4 # bottom left screen corner → desktop
    - wvous-bl-modifier -int 0
    - wvous-br-corner -int 2 # bottom right screen corner → mission control
    - wvous-br-modifier -int 0

- name: os config | notification settings
  tags: [os_config, notification]
  command: /usr/libexec/PlistBuddy -c {{ item }} {{ v_pref }}com.apple.notificationcenterui.plist
  with_items:
    - '"add :bannerTime integer 5"'
    - '"set :TodayView:preferences:com.apple.nc.disclosures:enabled integer 1"'
    - '"set :TodayView:preferences:com.apple.nc.social:enabled integer 0"'
    - '"set :TodayView:preferences:com.apple.nc.today.date:enabled integer 1"'
    - '"set :TodayView:preferences:com.apple.nc.today.dnd:enabled integer 1"'
    - '"set :TodayView:preferences:com.apple.nc.today.summary:enabled integer 0"'
    - '"set :TodayView:preferences:com.apple.nc.tomorrow.summary:enabled integer 0"'
    - '"add :TodayView:order:0 string com.apple.RemindersNC"'
    - '"add :TodayView:order:1 string com.apple.iCal.CalendarNC"'
    - '"add :TodayView:order:2 string com.apple.ncplugin.stocks"'
    - '"add :TodayView:order:3 string com.apple.ncplugin.weather"'
    - '"add :TodayView:order:4 string com.apple.nc.social"'
    - '"add :TodayView:order:5 string com.apple.iTunes.today.TodayExtension"'
    - '"add :TodayView:order:6 string com.apple.ncplugin.calculator"'
    - '"add :TodayView:order:7 string com.apple.ncplugin.WorldClock"'
  ignore_errors: yes

- name: os config | notification settings
  tags: [os_config, notification]
  command: defaults read {{ v_pref }}com.apple.notificationcenterui.plist
  # refresh cache

- name: os config | spotlight settings
  tags: [os_config, spotlight]
  command: defaults write com.apple.Spotlight {{ item }}
  with_items:
    - orderedItems -array \
      '{"enabled" = 1;"name" = "APPLICATIONS";}' \
      '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
      '{"enabled" = 1;"name" = "MENU_EXPRESSION";}' \
      '{"enabled" = 1;"name" = "MENU_CONVERSION";}' \
      '{"enabled" = 1;"name" = "MENU_DEFINITION";}' \
      '{"enabled" = 1;"name" = "DOCUMENTS";}' \
      '{"enabled" = 1;"name" = "PRESENTATIONS";}' \
      '{"enabled" = 1;"name" = "SPREADSHEETS";}' \
      '{"enabled" = 1;"name" = "PDF";}' \
      '{"enabled" = 1;"name" = "MESSAGES";}' \
      '{"enabled" = 1;"name" = "CONTACT";}' \
      '{"enabled" = 1;"name" = "EVENT_TODO";}' \
      '{"enabled" = 0;"name" = "DIRECTORIES";}' \
      '{"enabled" = 0;"name" = "IMAGES";}' \
      '{"enabled" = 0;"name" = "BOOKMARKS";}' \
      '{"enabled" = 0;"name" = "MUSIC";}' \
      '{"enabled" = 0;"name" = "MOVIES";}' \
      '{"enabled" = 0;"name" = "FONTS";}' \
      '{"enabled" = 0;"name" = "MENU_OTHER";}' \
      '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}' \
      '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}'
    - version -int 7

- name: os config | screenshot settings
  tags: [os_config]
  command: defaults write com.apple.screencapture {{ item }}
  with_items:
    - disable-shadow -bool true # disable shadow in screenshots
    - location -string "${HOME}/Desktop" # save screenshots to the desktop
    - type -string "png" # save screenshots as PNG (BMP, GIF, JPG, PDF, TIFF)

- name: os config | app layer firewall settings
  tags: [os_config]
  sudo: yes
  command: defaults write /Library/Preferences/com.apple.alf {{ item }}
  with_items:
    - globalstate -int 2 # firewall on for essential services & block all others
    - stealthenabled -bool true # enable stealth mode

- name: os config | activity monitor settings
  tags: [os_config, activity]
  command: defaults write com.apple.ActivityMonitor {{ item }}
  with_items:
    - IconType -int 5 # visualize CPU usage in dock icon
    - OpenMainWindow -bool true # show main window @launch
    - ShowCategory -int 100 # show all processes
    - "\"UserColumnsPerTab v4.0\" -dict '0' '( Command, CPUUsage, CPUTime, Threads, IdleWakeUps, PID, UID )'"
    - "\"UserColumnsPerTab v4.0\" -dict '1' '( Command, anonymousMemory, Threads, Ports, PID, UID, ResidentSize )'"
    - "\"UserColumnsPerTab v4.0\" -dict '2' '( Command, PowerScore, 12HRPower, AppSleep, graphicCard, UID )'"
    - "\"UserColumnsPerTab v4.0\" -dict '3' '( Command, bytesWritten, bytesRead, Architecture, PID, UID, CPUUsage )'"
    - "\"UserColumnsPerTab v4.0\" -dict '4' '( Command, txBytes, rxBytes, txPackets, rxPackets, PID, UID, CPUUsage )'"
    - UserColumnSortPerTab -dict '0' '{ direction = 0; sort = CPUUsage; }'
    - UserColumnSortPerTab -dict '1' '{ direction = 0; sort = ResidentSize; }'
    - UserColumnSortPerTab -dict '2' '{ direction = 0; sort = 12HRPower; }'
    - UserColumnSortPerTab -dict '3' '{ direction = 0; sort = CPUUsage; }'
    - UserColumnSortPerTab -dict '4' '{ direction = 0; sort = CPUUsage; }'
    - SelectedTab -int 4 # select the Network tab
    - UpdatePeriod -int 2 # 2 seconds
    - DiskGraphType -int 1 # show data in disk graph (not IO)
    - NetworkGraphType -int 1 # show data in network graph (not packets)

- name: os config | disk image settings
  tags: [os_config]
  command: defaults write com.apple.frameworks.diskimages {{ item }}
  with_items:
    - skip-verify -bool true # disable disk image verification
    - skip-verify-locked -bool true # "
    - skip-verify-remote -bool true # "
    - auto-open-ro-root -bool false # don't show finder on new mount
    - auto-open-rw-root -bool false # "

- name: os config | set scrollbar click action to jump to corresponding spot
  tags: [os_config]
  command: defaults write -g AppleScrollerPagingBehavior -bool true

- name: os config | misc nsglobal settings
  tags: [os_config, nsglobal]
  command: defaults write NSGlobalDomain {{ item }}
  with_items:
    - AppleEnableSwipeNavigateWithScrolls -bool true # 2-finger swipe between pages with two fingers
    - AppleFontSmoothing -int 2 # enable subpixel fonts @non-Apple LCDs
    - AppleICUForce12HourTime -bool false
    - AppleKeyboardUIMode -int 3 # enable tab in modal dialogs
    - ApplePressAndHoldEnabled -bool false # enable key repeat
    - AppleScrollAnimationEnabled -bool true # use smooth scrolling
    - AppleShowAllExtensions -bool true # show filename extensions
    - KeyRepeat -int 2 # key repeat speed
#    - NSAutomaticQuoteSubstitutionEnabled -bool false # kill smart quotes
#    - NSAutomaticDashSubstitutionEnabled -bool false # kill smart dashes
#    - NSAutomaticSpellingCorrectionEnabled -bool false # kill auto-correct
    - NSDocumentSaveNewDocumentsToCloud -bool false # default save to disk, not to iCloud
    - NSNavPanelExpandedStateForSaveMode -bool true # expand save panel by default
    - NSNavPanelExpandedStateForSaveMode2 -bool true # expand save panel by default
    - NSTableViewDefaultSizeMode -int 2 # set sidebar icon size to medium
    - NSWindowResizeTime -float 0.001 # speed up window resize @Cocoa apps
    - PMPrintingExpandedStateForPrint -bool true # expand print panel by default
    - PMPrintingExpandedStateForPrint2 -bool true # expand print panel by default
    - com.apple.springing.enabled -bool true # enable dir spring loading
    - com.apple.springing.delay -float 0 # kill dir spring loading delay
    - com.apple.mouse.tapBehavior -int 1 # enable tap to click

- name: os config | enable tap to click
  tags: [os_config]
  command: defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

- name: os config | disable crash reporter
  tags: [os_config]
  command: defaults write com.apple.CrashReporter DialogType -string "none"

- name: os config | check for software updates daily
  tags: [os_config]
  command: defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

- name: os config | enable Time Machine
  tags: [os_config, tm]
  sudo: yes
  command: tmutil {{ item }}
  with_items:
    - enable
    - disablelocal

- name: os config | time machine settings
  tags: [os_config, tm]
  sudo: yes
  command: defaults write /Library/Preferences/com.apple.TimeMachine {{ item }}
  with_items:
    - AlwaysShowDeletedBackupsWarning -bool true
    - AutoBackup -bool true
    - DoNotOfferNewDisksForBackup -bool true
    - RequiresACPower -bool false
    - SkipSystemFiles -bool true

- name: os config | kill time machine notifications
  tags: [os_config, tm]
  shell: sqlite3 $(echo $(getconf DARWIN_USER_DIR)/com.apple.notificationcenter/db/db) "UPDATE app_info SET flags='12609' WHERE bundleid = '_SYSTEM_CENTER_:com.apple.TMHelperAgent'";

- name: os config | show battery percentage remaining
  tags: [os_config, battery]
  command: defaults write com.apple.menuextra.battery ShowPercent -string "YES"

- name: os config | don't create .ds_store files on network volumes
  tags: [os_config]
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: os config | set menu clock format
  tags: [os_config, clock]
  command: defaults write com.apple.menuextra.clock DateFormat -string "EEE MMM d  h:mm a"

- name: os config | set desktop picture
  tags: [os_config]
  command: "{{ item }}"
  with_items:
    - rm -f ~/Library/Application\ Support/Dock/desktoppicture.db
    - sudo ln -sf /Library/Desktop\ Pictures/Hawaiian\ Print.jpg /System/Library/CoreServices/DefaultDesktop.jpg

- name: os config | increase bluetooth audio quality
  tags: [os_config]
  command: defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

- name: os config | set "paste and match sytle" to option + cmd + v
  tags: [os_config]
  command: defaults write .GlobalPreferences NSUserKeyEquivalents '{ "Paste and Match Style" = "~@v"; }'
  # notes: command = @, shift = $, control = ^, option = ~

- name: os config | automatically quit printer app after printing
  tags: [os_config]
  command: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

- name: os config | disable the “are you sure you want to open this application?” dialog
  tags: [os_config]
  command: defaults write com.apple.LaunchServices LSQuarantine -bool false

- name: os config | kill dups in "open with" menu
  tags: [os_config]
  command: /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

- name: os config | set help viewer windows to non-floating mode
  tags: [os_config]
  command: defaults write com.apple.helpviewer DevMode -bool true

- name: os config | restart automatically if mac freezes
  tags: [os_config]
  sudo: yes
  command: systemsetup -setrestartfreeze on

- name: os config | disable boot time sound effects
  tags: [os_config]
  sudo: yes
  command: nvram SystemAudioVolume=%80

- name: os config | create symlinks
  tags: [os_config, symlink]
  sudo: yes
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ v_user }}
  with_items:
    - { src: 'bash_profile', dest: '{{ v_home }}.bash_profile' }
    - { src: 'bashrc-jp',    dest: '{{ v_home }}.bashrc' }

- name: os config | create new user
  tags: [os_config]
  sudo: yes
  command: dscl . {{ item }}
  with_items:
    - create /Users/{{ admin_user }}
    - create /Users/{{ admin_user }} RealName {{ admin_userRN }}
    - passwd /Users/{{ admin_user }} {{ admin_userPass }}
    - create /Users/{{ admin_user }} UniqueID 550
    - create /Users/{{ admin_user }} PrimaryGroupID 80
    - create /Users/{{ admin_user }} UserShell /bin/bash
    - create /Users/{{ admin_user }} NFSHomeDirectory /Users/{{ admin_user }}
    - create /Users/{{ admin_user }} IsHidden 1
    - create /Users/{{ admin_user }} hint {{ admin_userHint }}

- name: app | chown brew & brew cask directories
  tags: [os_config, chown]
  sudo: yes
  command: chown -R {{ admin_user }} {{ item }}
  with_items:
    - ' /usr/local'
    - ' /opt/homebrew-cask'
    - ' /Library/Caches/Homebrew'

- name: os config | allow fast user switching
  tags: [os_config]
  sudo: yes
  command: defaults write /Library/Preferences/.GlobalPreferences MultipleSessionEnabled -bool true

- name: os config | kill default share points
  tags: [os_config, shares]
  sudo: yes
  # command: dscl . -delete "/SharePoints/{{ item }}'s Public Folder"
  command: rm -rf /Users/{{ item }}/Public
  with_items:
    - '{{ v_user }}'
    - '{{ admin_user }}'
    - Guest

- name: os config | downgrade non-admin user account
  tags: [os_config, downgrade]
  sudo: yes
  command: dseditgroup -o edit -d {{ v_user }} -t user admin

- name: os config | kill retry file
  tags: [os_config]
  command: rm -f ~/playbook.retry

- name: os config | all done!
  tags: [os_config, voice]
  osx_say: 'msg="{{ item }}" voice={{ v_voice }}'
  with_items:
    - os config playlist is complete
    - no more playlists
    - mac will now reboot

- name: os config | reboot
  tags: [os_config]
  sudo: yes
  command: shutdown -r now
  async: 0
  poll: 0
  ignore_errors: true
